version: '3'
services:
  nodejs:
    build: .
    container_name: 'lights'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ./entrypoint.sh
